# Generated by Django 3.1.7 on 2021-04-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210407_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
