# Generated by Django 3.1.7 on 2021-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210401_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_duration',
            new_name='estimated_duration_mins',
        ),
        migrations.AddField(
            model_name='task',
            name='task_setter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Open', max_length=200),
        ),
    ]
